#include <stdint.h>
#include <stdio.h>

#include "aes256.h"

// Tests the aes256.c routines against key/pt/ct generated by another independent source and provided in tests.txt

// Example tests.txt
// hex key, followed by hex 'plaintext' and hex ciphertext as matching triple 
/* BEGINS on next line
2ba99bbe684d1fb3a56a69e2a459c6f24d7094373327a3cddddfb0f4b5bbcd46 32106c60850e5d6a2679308569b19873 e309505fef59bddc60f834a10a9926e2
c8fbb5f35351110027bed02b3d75eb1a2151b16ccb28c95905f60662e584a6a7 7cf9cf077b2f2eacee9058daaeb7adbf a1a31b680c76e97b1b435f48c77ea170
ENDS on previous line */

#define TESTS_IN_FILE (2) // Have used 1000000, with suitable file

void main() {
  
  uint8_t key[32];
  uint8_t state[32];
  uint8_t target[32];

  FILE *file_ptr; // No error checking whatsoever, expect file to be there with "TESTS_IN_FILE" tests
  // Ugly bare minimum code - and note point about line endings may be os dependent.

  file_ptr = fopen("tests.txt", "r");
  uint32_t successful=0;
  for (uint32_t i=0;i<TESTS_IN_FILE;i++) {  

    for (uint8_t j=0;j<32;j++) {
      uint8_t accumulator=0;
      char c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator=(c - 'a' + 10);
        
      accumulator<<=4;
      c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator|=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator|=(c - 'a' + 10);
          
      *(key+j)=accumulator;
    }
    fgetc(file_ptr); // Skip space
    
    for (uint8_t j=0;j<16;j++) {
      uint8_t accumulator=0;
      char c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator=(c - 'a' + 10);
        
      accumulator<<=4;
      c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator|=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator|=(c - 'a' + 10);
      *(state+j)=accumulator;
    }
    fgetc(file_ptr); // Skip space
    
    for (uint8_t j=0;j<16;j++) {
      uint8_t accumulator=0;
      char c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator=(c - 'a' + 10);
        
      accumulator<<=4;
      c=fgetc(file_ptr);
      if (c>='0' && c<='9')
        accumulator|=(c - '0');
      else if( c>='a' && c<='f') // lower case
        accumulator|=(c - 'a' + 10);
      *(target+j)=accumulator;
    }
    fgetc(file_ptr); // Skip newline *** ADJUST AS REQUIRED FOR OS LINE ENDINGS
    fgetc(file_ptr); // Skip newline
    
    AES256_Encrypt(key,state);

    uint8_t pass=1;
    for (int j=0;j<16;j++) pass&=(state[j]==target[j]);
    printf("Encryption test %d : %s\n",i,pass?"PASS":"**FAIL**");
    if (pass) successful++;
  }
  fclose(file_ptr);
  printf("Successes = %d out of %d\n",successful,TESTS_IN_FILE);
}
